a=int(input("enter the first number:"))
b=int(input("enter the second number:"))
print("Equal:",a==b)
print("not equal:",a!=b)
print("greater_than:",a>b)
print("less_than:",a<b)
print("greater_than_equal:",a>=b)
print("less_than_equal:",a<=b)